package gestioninformacionproyectos.View;

import gestioninformacionproyectos.Controller.Export;
import gestioninformacionproyectos.Controller.ListingsController;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jaflorez
 */
public class Listings extends javax.swing.JInternalFrame {
    
    String name;
    String vecTit[];

    public Listings() {
        initComponents();
        tblMaster.setVisible(false);
        btnExport.setEnabled(false);
        this.name = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaster = new javax.swing.JTable();
        btnProyectWithActivity = new javax.swing.JButton();
        btnOwnerWithActivity = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnExport = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("LISTADOS");

        jScrollPane1.setViewportView(tblMaster);

        btnProyectWithActivity.setText("Listado de Proyectos con sus actividades");
        btnProyectWithActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProyectWithActivityActionPerformed(evt);
            }
        });

        btnOwnerWithActivity.setText(" Listados de Responsables con sus actividades");
        btnOwnerWithActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOwnerWithActivityActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Haga clic en cualquiera de los dos botones para ver sus respectivos listados.");

        btnExport.setText("Exportar a archivo plano");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnProyectWithActivity)
                                .addGap(18, 18, 18)
                                .addComponent(btnOwnerWithActivity)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(105, 105, 105))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnExport)
                                        .addGap(1, 1, 1)))
                                .addGap(24, 24, 24))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProyectWithActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOwnerWithActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExport)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProyectWithActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProyectWithActivityActionPerformed
        this.name = "Listado de Proyectos con sus actividades";
        tblMaster.setVisible(true);
        ListingsController listingsController = new ListingsController();
        String[][] matriz = listingsController.consultProyectWithActivity();
        
        lblTitle.setText("Listado de Proyectos con sus actividades");
        Object objMat[][] = new String[matriz.length][9];
        this.vecTit = new String[9];
        this.vecTit[0] = "Código Proyecto";
        this.vecTit[1] = "Título Proyecto";
        this.vecTit[2] = "Fecha Inicio Proyecto";
        this.vecTit[3] = "Fecha Fin Proyecto";
        this.vecTit[4] = "Costo Proyecto";
        this.vecTit[5] = "Código Actividad";
        this.vecTit[6] = "Descripción Actividad";
        this.vecTit[7] = "Fecha Inicio Actividad";
        this.vecTit[8] = "Fecha Fin Actividad";
        
        for(int i = 0; i < matriz.length; i++){
            objMat[i][0] = matriz[i][0];
            objMat[i][1] = matriz[i][1];
            objMat[i][2] = matriz[i][2];
            objMat[i][3] = matriz[i][3];
            objMat[i][4] = "$ " + matriz[i][4];
            objMat[i][5] = matriz[i][5];
            objMat[i][6] = matriz[i][6];
            objMat[i][7] = matriz[i][7];
            objMat[i][8] = matriz[i][8];
        }
        DefaultTableModel objModelo = new DefaultTableModel(objMat, this.vecTit);
        tblMaster.setModel(objModelo);
        btnExport.setEnabled(true);
    }//GEN-LAST:event_btnProyectWithActivityActionPerformed

    private void btnOwnerWithActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOwnerWithActivityActionPerformed
        this.name = "Listados de Responsables con sus actividades";
        tblMaster.setVisible(true);
        ListingsController listingsController = new ListingsController();
        String[][] matriz = listingsController.consultOwnerWithActivity();
        
        lblTitle.setText("Listados de Responsables con sus actividades");
        Object objMat[][] = new String[matriz.length][8];
        this.vecTit = new String[8];
        this.vecTit[0] = "Código Responsable";
        this.vecTit[1] = "Nombre Responsable";
        this.vecTit[2] = "Número Fijo";
        this.vecTit[3] = "Número Móvil";
        this.vecTit[4] = "Código Actividad";
        this.vecTit[5] = "Descripción Actividad";
        this.vecTit[6] = "Fecha Inicio Actividad";
        this.vecTit[7] = "Fecha Fin Actividad";
        
        for(int i = 0; i < matriz.length; i++){
            objMat[i][0] = matriz[i][0];
            objMat[i][1] = matriz[i][1];
            objMat[i][2] = matriz[i][2];
            objMat[i][3] = matriz[i][3];
            objMat[i][4] = matriz[i][4];
            objMat[i][5] = matriz[i][5];
            objMat[i][6] = matriz[i][6];
            objMat[i][7] = matriz[i][7];
        }
        DefaultTableModel objModelo = new DefaultTableModel(objMat,this.vecTit);
        tblMaster.setModel(objModelo);
        btnExport.setEnabled(true);
    }//GEN-LAST:event_btnOwnerWithActivityActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        String cadena = "";
        String data[] = null;
        data  = new String [tblMaster.getRowCount()];
        for(int i = 0; i < tblMaster.getRowCount(); i++){
            for(int j=0; j < tblMaster.getColumnCount(); j++){
                if(j == this.vecTit.length - 1) {
                    cadena += this.vecTit[j].toUpperCase() + ": " + tblMaster.getValueAt(i, j).toString();
                } else {
                    cadena += this.vecTit[j].toUpperCase() + ": " + tblMaster.getValueAt(i, j).toString() + ", ";
                }
            }
          data[i] = cadena;
          cadena = "";
        }
        
        Export objExport = new Export();
        objExport.exportToTxt(data, name);
    }//GEN-LAST:event_btnExportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnOwnerWithActivity;
    private javax.swing.JButton btnProyectWithActivity;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblMaster;
    // End of variables declaration//GEN-END:variables
}
