package gestioninformacionproyectos.View;

import gestioninformacionproyectos.Controller.UserController;
import gestioninformacionproyectos.Model.User;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author srestrepo
 */
public class SingIn extends javax.swing.JFrame {

    /**
     * Creates new form SingIn
     */
    public SingIn() {
        initComponents();
        this.setLocationRelativeTo(null);
        try{
            setIconImage(new ImageIcon(getClass().getResource("/media/icono.jpg")).getImage());
        }catch(Exception e){
            System.out.println("no encuentra icono");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnCreateUser = new javax.swing.JButton();
        lblLogIn = new javax.swing.JLabel();
        txtContrasenha = new javax.swing.JPasswordField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(getIconImages());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Crear usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 34));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Para empezar a gestionar proyectos debe crear una cuenta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 340, 36));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Documento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        getContentPane().add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 340, 35));

        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Nombre");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 340, 34));

        Apellido.setForeground(new java.awt.Color(255, 255, 255));
        Apellido.setText("Apellido");
        getContentPane().add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Correo Electrónico");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 340, 34));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 340, 34));

        btnCreateUser.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCreateUser.setText("Crear cuenta");
        btnCreateUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 148, 41));

        lblLogIn.setForeground(new java.awt.Color(255, 255, 255));
        lblLogIn.setText("¿Ya tienes una cuenta?  inicia sesión aquí.");
        lblLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogInMouseClicked(evt);
            }
        });
        getContentPane().add(lblLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));
        getContentPane().add(txtContrasenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 340, 34));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // TODO add your handling code here:
        User user;
        UserController userController;
        String documento, nombre, apellido, correo, password = "";
        
        documento = txtDocumento.getText();
        nombre = txtNombre.getText();
        apellido = txtApellido.getText();
        correo = txtCorreo.getText();
        
        if("".equalsIgnoreCase(documento) || "".equalsIgnoreCase(nombre) ||
            "".equalsIgnoreCase(apellido) || "".equalsIgnoreCase(correo) ||
                txtContrasenha.getPassword().length == 0){
            JOptionPane.showMessageDialog(null, "Debe rellenar todos los campos obligatorios");
        } else {
            for (int i = 0; i < txtContrasenha.getPassword().length; i++) {
                password = password + txtContrasenha.getPassword()[i];
            }
            user = new User(documento, nombre, apellido, correo, password);
            userController = new UserController(user);
            if(!userController.consultUser(documento)) {
                userController.createUser();
                JOptionPane.showMessageDialog(null, "Usuario creado exitosamente, ahora puede iniciar sesión e ingresar al sistema");
                Login logIn = new Login();
                this.setVisible(false);
                logIn.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "Ya existe un usuario registrado con ese documento");
            }
        }
        
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void lblLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogInMouseClicked
        // TODO add your handling code here:
        Login logIn = new Login();
        this.setVisible(false);
        logIn.setVisible(true);
    }//GEN-LAST:event_lblLogInMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SingIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SingIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SingIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SingIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SingIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblLogIn;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContrasenha;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
