package gestioninformacionproyectos.View;

import gestioninformacionproyectos.Configuration.SessionData;
import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author srestrepo
 */
public class Start extends javax.swing.JFrame {
    
    SessionData session;
    
    public Start(SessionData sessionData) {
        this.session = sessionData;
        initComponents();
        try{
            setIconImage(new ImageIcon(getClass().getResource("/media/icono.jpg")).getImage());
        }catch(Exception e){
            System.out.println("no encuentra icono");
        }    
        desktop.setBorder(javax.swing.BorderFactory.createTitledBorder("Bienvenido " + sessionData.getName()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        INICIO = new javax.swing.JMenuBar();
        registro = new javax.swing.JMenu();
        projects = new javax.swing.JMenuItem();
        activities = new javax.swing.JMenuItem();
        owners = new javax.swing.JMenuItem();
        activitiesByProjectWithOwners = new javax.swing.JMenuItem();
        listings = new javax.swing.JMenuItem();
        logOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        desktop.setBackground(new java.awt.Color(0, 0, 0));
        desktop.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BIENVENIDO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        desktop.setToolTipText("");
        desktop.setAutoscrolls(true);
        desktop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        desktop.setName("BIENVENIDO"); // NOI18N

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );

        INICIO.setToolTipText("INICIO");
        INICIO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        INICIO.setName("INICIO"); // NOI18N

        registro.setText("REGISTRO");

        projects.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        projects.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/projects.png"))); // NOI18N
        projects.setText("Proyectos");
        projects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectsActionPerformed(evt);
            }
        });
        registro.add(projects);

        activities.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        activities.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/activity.png"))); // NOI18N
        activities.setText("Actividades");
        activities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activitiesActionPerformed(evt);
            }
        });
        registro.add(activities);

        owners.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        owners.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/person.png"))); // NOI18N
        owners.setText("Responsables");
        owners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownersActionPerformed(evt);
            }
        });
        registro.add(owners);

        activitiesByProjectWithOwners.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        activitiesByProjectWithOwners.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/elnace.png"))); // NOI18N
        activitiesByProjectWithOwners.setText("Actividades por Proyectos con Responsables");
        activitiesByProjectWithOwners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activitiesByProjectWithOwnersActionPerformed(evt);
            }
        });
        registro.add(activitiesByProjectWithOwners);

        listings.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        listings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/create.png"))); // NOI18N
        listings.setText("Listados");
        listings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listingsActionPerformed(evt);
            }
        });
        registro.add(listings);

        logOut.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/salir.png"))); // NOI18N
        logOut.setText("Terminar");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        registro.add(logOut);

        INICIO.add(registro);

        setJMenuBar(INICIO);
        INICIO.getAccessibleContext().setAccessibleName("INICIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop))
        );

        desktop.getAccessibleContext().setAccessibleParent(desktop);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void activitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activitiesActionPerformed
        ActivitysFrm objActivityFrm = new ActivitysFrm ();
        if(desktop.getComponentCount() == 0) {
            desktop.add(objActivityFrm);
            objActivityFrm.show();
        } else {
            Component oldFrame = desktop.getComponent(0);
            oldFrame.setVisible(false);
            desktop.add(objActivityFrm);
            objActivityFrm.show();
        }
    }//GEN-LAST:event_activitiesActionPerformed

    private void projectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectsActionPerformed
        projectFrm objProjectFrm = new projectFrm();
        if(desktop.getComponentCount() == 0) {
            desktop.add(objProjectFrm);
            objProjectFrm.show();
        } else {
            Component oldFrame = desktop.getComponent(0);
            oldFrame.setVisible(false);
            desktop.add(objProjectFrm);
            objProjectFrm.show();
        }
        
    }//GEN-LAST:event_projectsActionPerformed

    private void ownersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownersActionPerformed
        OwnersFrm objOwnersFrm = new OwnersFrm();
        if(desktop.getComponentCount() == 0) {
            desktop.add(objOwnersFrm);
            objOwnersFrm.show();
        } else {
            Component oldFrame = desktop.getComponent(0);
            oldFrame.setVisible(false);
            desktop.add(objOwnersFrm);
            objOwnersFrm.show();
        }
    }//GEN-LAST:event_ownersActionPerformed

    private void activitiesByProjectWithOwnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activitiesByProjectWithOwnersActionPerformed
        ActivitiesXProject_OwmersFrm objAPO = new ActivitiesXProject_OwmersFrm();
        if(desktop.getComponentCount() == 0) {
            desktop.add(objAPO);
            objAPO.show();
        } else {
            Component oldFrame = desktop.getComponent(0);
            oldFrame.setVisible(false);
            desktop.add(objAPO);
            objAPO.show();
        }
    }//GEN-LAST:event_activitiesByProjectWithOwnersActionPerformed

    private void listingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listingsActionPerformed
        // TODO add your handling code here:
        Listings listings = new Listings();
        if(desktop.getComponentCount() == 0) {
            desktop.add(listings);
            listings.show();
        } else {
            Component oldFrame = desktop.getComponent(0);
            oldFrame.setVisible(false);
            desktop.add(listings);
            listings.show();
        }
    }//GEN-LAST:event_listingsActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, 
                "Hola " + this.session.getName() + ", ¿Desea cerrar sesión?", "Cerrar sesión", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(resp == 0) {
            this.session.setOpenSession(false);
            this.session = null;
            this.setVisible(false);
            
            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_logOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], SessionData sessionData) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Start(sessionData).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar INICIO;
    private javax.swing.JMenuItem activities;
    private javax.swing.JMenuItem activitiesByProjectWithOwners;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem listings;
    private javax.swing.JMenuItem logOut;
    private javax.swing.JMenuItem owners;
    private javax.swing.JMenuItem projects;
    private javax.swing.JMenu registro;
    // End of variables declaration//GEN-END:variables
}
